spring.application.name=todo-management

#SQLの実行モードの設定
#アプリ実行時にschema.sqlとdata.sqlでテーブル作成とデータ投入を自動実行するための設定
spring.sql.init.mode=always

#データベースの設定

#H2がsampledbという名前でメモリ上で動作するように設定
spring.datasource.url=jdbc:h2:mem:sampledb
#H2のドライバーを使用することを設定
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=12345

#Mybatisの設定
mybatis.configuration.map-underscore-to-camel-case=true