CREATE TABLE todos (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    task VARCHAR(255) NOT NULL,
    deadline DATE NOT NULL,
    category VARCHAR(255) NOT NULL,
    place VARCHAR(255),
    memo VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    isTodoflag BOOLEAN DEFAULT FALSE
);

 CREATE TABLE users (
    user_id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(60) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
 );